name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    env:
      NAME: polong-core
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        sh build.sh

    - name: Create release and upload assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        files: 'build/*'
