name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    env:
      NAME: polong-core
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        sh build.sh

    - name: Upload
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        sudo apt-get install -y jq
        GIT_TAG=`echo $GITHUB_REF | sed 's/refs\/tags\///'`
        upload_url=`curl \
        -X POST \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${GITHUB_REPOSITORY}/releases \
        -d '{"tag_name":"'${GIT_TAG}'"}' \
        | jq --raw-output '.upload_url' \
        | sed 's/{?name,label}/?name/'`
        # upload
        curl \
        -X POST \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        -H "Accept: application/vnd.github.v3+json" \
        -F 'file=@build/polong-core-linux' \
        ${upload_url}=polong-core-linux
        # upload
        curl \
        -X POST \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        -H "Accept: application/vnd.github.v3+json" \
        -F 'file=@build/polong-core-windows' \
        ${upload_url}=polong-core-windows
        # upload
        curl \
        -X POST \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        -H "Accept: application/vnd.github.v3+json" \
        -F 'file=@build/polong-core.aar' \
        ${upload_url}=polong-core.aar
