name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    env:
      NAME: polong-core
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        go mod download
        mkdir build
        echo "Linux"
        go build -o "build/${NAME}-linux"
        echo "Windows"
        sudo apt install -y gcc-multilib gcc-mingw-w64
        GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -o "build/${NAME}-windows"
        echo "Android"
        go get golang.org/x/mobile/cmd/gomobile
        gomobile init
        gomobile bind -target=android/arm64,android/arm -o "build/${NAME}.aar" ./kc ./qc
        rm "build/${NAME}-sources.jar"

    - name: Create release and upload assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        files: 'build/*'
